### ISSUE TITLE
SMS from way2sms site - Not Working

### ISSUE THREAD

**Issue by shivdhwaj** [dhruvbaldawa/Tutorials#3]
No error every thing says fine logged in and sent successfully but the user doesnt get the sms.

**Comment by dhruvbaldawa** [comment]
I am sorry those scripts are really old now and are not up-to-date with the latest changes. The SMS websites are also smarter now and its not easy to make them work again.
They are just there for educational purposes now.

**Comment by shivdhwaj** [comment]
Can we bring it up again ?

**Comment by dhruvbaldawa** [comment]
Sorry mate, the sites are smarter now. The last time I tried it didn't seem so easy to get through.
